keys:
  - &server age1uahmnuqv3mtdpp7vnlswr2jvwpllcf04eewvmlwrj7fj3qr8weaqehkjh2
  - &test_vm age12v8lf3ftqdvcemkrl3mlv435sdq6ejwmjdup4kh3x7n2sclpqu8qk25v0r
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *server
        - *test_vm
        
