keys:
  - &server age1ed6mlfkrhtnr6gq79hff3shc5eygp3547ftx4c7hqxektue8najs5z2nn9
  - &test_vm age12v8lf3ftqdvcemkrl3mlv435sdq6ejwmjdup4kh3x7n2sclpqu8qk25v0r
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *server
        - *test_vm
        
